services:
  <redis-service-name>:
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      service-backbone-shared:
        aliases:
          - redis

networks:
  service-backbone-shared:
    external: true
    name: service-backbone-shared
